# Generated by Django 4.1.3 on 2022-11-03 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('musicapp', '0002_song_artiste_song_artiste_idno_song_date_released_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lyric',
            name='Song',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='musicapp.song'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='content',
            field=models.CharField(default=1, max_length=400),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lyric',
            name='song_idNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
